apiVersion: apps/v1
kind: Deployment
metadata:
  name: malone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: malone
  template:
    metadata:
      labels:
        app: malone
    spec:
      containers:
        - name: malone
          image: ghcr.io/tonygilkerson/malone:v1.0.17
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: 250m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
